### ISSUE TITLE
openvino_inference.py 'ImageResult' object has no attribute 'anomalous_boxes' or 'heat_map'

### ISSUE THREAD

**Issue by rvermeire** [openvinotoolkit/anomalib#1005]
When I invoke openvino_inference.py with --task=detection or --task=segmentation I get `AttributeError: 'ImageResult' object has no attribute 'anomalous_boxes' or 'heat_map'` respectively

**Comment by samet-akcay** [comment]
Hi @rvermeire, thanks for your patience. 

I am unable to reproduce this. If you are still having this issue, can you provide your config file? 

When I use the following config file I have access to those attributes:

## Training
```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  task: segmentation
  category: bottle
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: 224 # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino    # options: onnx, openvino, torch

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

```bash
# Train the patchcore model.
python tools/train.py --model patchcore
```

## Inference
When you run the openvino inference via

This would have the following 
```python
>>> from anomalib.data.utils import read_image
>>> from anomalib.deploy import OpenVINOInferencer
>>> 
>>> inferencer = OpenVINOInferencer(
...    path="results/patchcore/mvtec/bottle/run/weights/openvino/model.bin",
...    metadata="results/patchcore/mvtec/bottle/run/weights/openvino/metadata.json",
...    device="CPU",
... )
>>> image = read_image("datasets/MVTec/bottle/test/broken_large/000.png")
>>> predictions = inferencer.predict(image=image)


# This should give the output you want
>>> predictions.heat_map.shape
(900, 900, 3)

>>> predictions.anomaly_map.shape
(900, 900)
```
