### ISSUE TITLE
[Task]: How to call onnx model to detect the presence of defects in images

### ISSUE THREAD

**Issue by laogonggong847** [openvinotoolkit/anomalib#1018]
### What is the motivation for this task?

Many thanks to all the members of the Anomalib team for open sourcing such an excellent tool. We have no doubt that the emergence of Anomalib will push the development of anomaly detection, and once again, we salute all the authors and contributors who have improved the Anomalib community.

After using ```padim``` in Anomalib to train my own dataset, I ended up with an ```onnx model``` because I set the export_mode in the corresponding config.yaml file to "onnx" ```(export_mode: "onnx")```. However, I was confused about how to call this model to inference.

I know that Anomalib provides 4 programs for inference under ```. /tools/inference```, which provides four programs for inference, and I am grateful to the developer for being so careful and comprehensive. But I'm new to onnx models, and I'm not sure if one of these four programs can be used directly to call onnx models, and if so, can you tell me explicitly which one it is. If not, can you tell me what I should do. Thank you very much!

### Describe the solution you'd like

I would like to understand the method and steps of calling ```onnx model``` to achieve detection, thank you very much. 

Besides that I have another question, ```why do I use a lot of CPU and memory resources when training padim models. While the GPU (RTX2080Ti) only takes up about 1%, sometimes even 0```

### Additional context

pytorch:     1.12.1+cu113
cuda:         11.3  ```(torch.cuda.is_available = True)```
python:      3.8
anomalib:  0.5.0.dev0 (latest)

Yaml:
```
dataset:
  name: mydata
  format: folder
  path: ./Mydatasets/cubes
  normal_dir: normal # 独有 name of the folder containing normal images.
  abnormal_dir: abnormal # 独有 name of the folder containing abnormal images.
  normal_test_dir: null # 独有 name of the folder containing normal test images.
  task: classification # classification or segmentation
  mask: null #optional
  extensions: null
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 4
  transform_config:
    train: null
    eval: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: from_dir # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.1 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 30
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle

```
