### ISSUE TITLE
[Bug]: image is not shown after set flag --show

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/anomalib#1127]
### Describe the bug
python3 tools/inference/openvino_inference.py --weights results/padim/pcb/run/weights/openvino/model.bin --metadata results/padim/pcb/run/weights/openvino/metadata.json --config src/anomalib/models/padim/config_pcb.yaml --input datasets/pcb/defective_test/012.jpg --task classification --show --output results/padim/pcb

the image is saved but not shown and program hang

### Dataset

Folder

### Model

PADiM

### Steps to reproduce the behavior

conda create -n anomalib_env python=3.10
conda activate anomalib_env
git clone https://github.com/openvinotoolkit/anomalib.git
cd anomalib
pip install -e .

### OS information

OS information:
- OS: [Ubuntu 20.04]
- Python version: [3.10.11]
- Anomalib version: [1.0.0.dev0]
- PyTorch version: [2.0.1]
- CUDA/cuDNN version: [11.7]
- GPU models and configuration: [GeForce RTX 3060]
- Any other relevant information: [I'm using a custom dataset]

### Expected behavior

image should display on screen

### Pip/GitHub

GitHub

### What version/branch did you use?

1.0.0dev

### Configuration YAML

```yaml
dataset:
  name: pcb
  format: folder
  root: ./datasets/pcb
  normal_dir: train # name of the folder containing normal images.
  abnormal_dir: defective_test # name of the folder containing abnormal images.
  task: segmentation # classification or segmentation
  mask_dir: defective_ground_truth #optional
  normal_test_dir: good_test # optional
  extensions: null
  split_ratio: 0.2  # normal images ratio to create a test split
  seed: 0
  image_size: 256
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  normalization: imagenet # data distribution to which the images will be normalized
  test_split_mode: from_dir # options [from_dir, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  transform_config:
      train: null
      eval: null
  val_split_mode: from_test # determines how the validation set is created, options [same_as_test, from_test]
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: True # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
no error logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
