### ISSUE TITLE
📚 Improve documentation on using different backbones

### ISSUE THREAD

**Issue by ninafiona** [openvinotoolkit/anomalib#1144]
### What is the motivation for this task?

I want to try different backbones (EfficientNet, ViT, MobileNet, ...), but there is not much documentation on it. 
I tried this configuration, but `blocks.4` was not recognized. 
```
model:
  name: patchcore
  backbone: efficientnet_b4  # wide_resnet50_2, resnet18
  pre_trained: true
  layers:
    # - layer2
    # - layer3
    - blocks.4
    - blocks.5
```

### Describe the solution you'd like

I would like information about which backbones are compatible and how to reference the mid-level feature layers.
