### ISSUE TITLE
[Task]: Add PadimModel n_features to configuration yaml file

### ISSUE THREAD

**Issue by fanchuanster** [openvinotoolkit/anomalib#1185]
### What is the motivation for this task?

Hi,
Thanks for the effort building such an awesome library.

Wondering is it OK to add n_features to the PaDiM yaml config file so that to be customizable through configuration?

https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/padim/torch_model.py#L49C7-L49C17
n_features (int, optional): Number of features to retain in the dimension reduction step.
Default values from the paper are available for: resnet18 (100), wide_resnet50_2 (550).

It is not there yet - https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/padim/config.yaml

### Describe the solution you'd like

Add n_features to the PaDiM yaml config file, or other advise, or explain why it should not be customized through config file.

**Comment by blaz-r** [comment]
Hello, this could be added, especially if you get any improvement. The authors of the model found that those values work the best in terms of speed and performance trade-off. It is possible that this doesn't reflect on all datasets. Do you by any chance have any evaluation data that would show different results while keeping the speed and performance?

**Comment by fanchuanster** [comment]
Hello, 
thanks for reply. I don't have any evaluation yet, but once it's customizable we would like to try 200 instead of 100 for resnet18.

**Comment by blaz-r** [comment]
Hello. I just checked the source code. This is [already included](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/padim/lightning_model.py#L129), just not present in config. All you need to add is `n_features: 200` in config under `model`. For example:
```yaml
model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]
  n_features: 200
```
