### ISSUE TITLE
[HELP] Segmentation task using only good/bad images (no masks)

### ISSUE THREAD

**Issue by FedericoDeBona** [openvinotoolkit/anomalib#1349]
Hello, 
I need to train a model based only on good/bad images without masks to perform **segmentation**, but I have some issues.
I first used Anomalib version 0.4.0 comparing a custom screw dataset with the MVTec screw dataset.

# Anomalib 0.4.0
## Custom dataset
This are examples of images from the custom dataset
| 0                           |  1                         |  2                        | 3                             |
| ----------------------------------- | ----------------------------------- | ----------------------------------- | ----------------------------------- |
| ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/c863469f-b225-467a-87d5-3b45449898f7) | ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/9195ad8b-9b94-41e3-8a43-2bb45c7fd339) |  ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/5260e247-c819-4a22-9424-51d396bd7d5d) |  ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/47c71137-c0cf-44d5-aea7-49dc8b4b197d)

With a total of 280 images.

This is the config.yaml using **Padim**
```yaml
dataset:
  name: screw
  format: folder
  path: /home/rdover/anomalib_test/screw/
  normal_dir: good # name of the folder containing normal images.
  abnormal_dir: null # name of the folder containing abnormal images.
  task: segmentation # classification or segmentation
  mask_dir: null #optional
  normal_test_dir: null # optional
  extensions: null
  split_ratio: 0.2  # normal images ratio to create a test split
  image_size: 960
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 12
  normalization: imagenet # data distribution to which the images will be normalized
  test_split_mode: from_dir # options [from_dir, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  transform_config:
      train: null
      eval: null
  val_split_mode: from_test # determines how the validation set is created, options [same_as_test, from_test]
```
Other settings are the defaults.

After training here's the results:

### Inference on good screw
| good_original                           |   good_inference                         |
| ----------------------------------- | ----------------------------------- |
![](https://github.com/openvinotoolkit/anomalib/assets/36895247/9b093def-d979-4ab9-9cb5-ca1a34b7bf02) | ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/5c9d94d0-351a-4f73-94b9-ce649d7807ae)

In this case the model recognizes a problem on the tip, but it's actually fine.

### Inference on a missing tip screw
| missing_tip_original                           |   missing_tip_inference                         |
| ----------------------------------- | ----------------------------------- |
![](https://github.com/openvinotoolkit/anomalib/assets/36895247/4c160e80-56f9-4ffe-b971-2afef251e42c) | ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/faf66fe0-5ba3-4a42-ada0-6933336176e0)

it recognizes that there are scratches, but not that the tip is missing.

## MVTec screw dataset
Same as before, the model is trained only on good images from the MVTec dataset. Here's the config file, again with ***padim***
```yaml
dataset:
  name: screw
  format: folder
  path: /home/rdover/anomalib/datasets/MVTec/screw/train/
  normal_dir: good # name of the folder containing normal images.
  abnormal_dir: null # name of the folder containing abnormal images.
  task: segmentation # classification or segmentation
  mask_dir: null #optional
  normal_test_dir: null # optional
  extensions: null
  split_ratio: 0.2  # normal images ratio to create a test split
  image_size: 256
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 12
  normalization: imagenet # data distribution to which the images will be normalized
  test_split_mode: from_dir # options [from_dir, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  transform_config:
      train: null
      eval: null
  val_split_mode: from_test # determines how the validation set is created, options [same_as_test, from_test]
```
### Inference on good screw
| good_original                           |   good_inference                         |
| ----------------------------------- | ----------------------------------- |
![](https://github.com/openvinotoolkit/anomalib/assets/36895247/894a0170-72b4-4847-bc9b-0f7a8e89d722) | ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/dbba69ab-2ce1-4207-9a0f-7c351e345712)

This is actually the worst case, but even with other good screw, the inference finds errors

### Inference on a screw with bad thread side
| thread_side_original                           |   thread_side_inference                         |
| ----------------------------------- | ----------------------------------- |
![](https://github.com/openvinotoolkit/anomalib/assets/36895247/18905999-ac7c-4812-a38d-630c3d4e4f89) | ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/29587cc4-af6f-49fe-ae1e-40b7d889162a)

The inference is not bad but the tip shouldn't be considered

### A nice inference on a bad screw
| scratch_neck_original                           |   scratch_neck_inference                         |
| ----------------------------------- | ----------------------------------- |
![](https://github.com/openvinotoolkit/anomalib/assets/36895247/6d925c89-3aa7-4875-af3d-da58b440a391) | ![](https://github.com/openvinotoolkit/anomalib/assets/36895247/63ff92e8-6dc6-4769-8787-16715d689f4e)

As you can see sometimes it works great

# Anomalib version 0.7.0
Using the latest version with this config on the custom dataset (this time using `abnormal_dir`):
```yaml
dataset:
  name: screw
  format: folder
  path: /home/rdover/anomalib_test/screw/
  normal_dir: good # name of the folder containing normal images.
  abnormal_dir: test/bad # name of the folder containing abnormal images.
  task: segmentation # classification or segmentation
  mask_dir: null #optional
  normal_test_dir: null # optional
  extensions: null
  split_ratio: 0.2  # normal images ratio to create a test split
  image_size: 960
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 12
  normalization: imagenet # data distribution to which the images will be normalized
  test_split_mode: from_dir # options [from_dir, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  transform_config:
      train: null
      eval: null
  val_split_mode: from_test # determines how the validation set is created, options [same_as_test, from_test]
```
I get this error:
`ValueError: Segmentation task requires mask directory if test_split_mode is from_dir. You could set test_split_mode to none or provide a mask directory.` so I change the config file as it suggest and do the training.

Now doing inference with this model, what I get is always an inference result of 0.5.

# Conclusions

Is there a way to achieve a model only using good/bad images, or even only good for a segmentation task?

**Comment by abc-125** [comment]
Hello,

> Is there a way to achieve a model only using good/bad images, or even only good for a segmentation task?

Most of the models here are trained with good images only, so it should be possible. 
You can change the task from segmentation to classification, so you won't get `ValueError: Segmentation task requires mask directory...` The output model will still be able to do segmentation anyway. Here is the corrected dataset config:
```
dataset:
  name: screw
  format: folder
  path: /home/rdover/anomalib_test/screw/
  normal_dir: good # name of the folder containing normal images.
  abnormal_dir: test/bad # name of the folder containing abnormal images.
  task: classification # classification or segmentation
  mask_dir: null #optional
  normal_test_dir: null # optional
  extensions: null
  split_ratio: 0.2  # normal images ratio to create a test split
  image_size: 256
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 12
  normalization: imagenet # data distribution to which the images will be normalized
  test_split_mode: from_dir # options [from_dir, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  transform_config:
      train: null
      eval: null
  val_split_mode: from_test # determines how the validation set is created, options [same_as_test, from_test]
```

> an inference result of 0.5.

It's hard to say why you got this result. You can try to use the config above. I tested it with the PatchCore model (make sure you are using its `config.yaml` and change only `dataset`), and it worked well.

> In this case the model recognizes a problem on the tip, but it's actually fine.
it recognizes that there are scratches, but not that the tip is missing.

I might suggest changing the image size in your config from 960x960 to 256x256 (like in the MVTec AD dataset). 

Hope that helps!
