### ISSUE TITLE
[Bug]: PADiM output nan values when using one normal sample as training data.

### ISSUE THREAD

**Issue by Hunter-Will** [openvinotoolkit/anomalib#1430]
### Describe the bug

I was trying to test 1-shot performance of PADiM and I reduce the number of training data by modifying the mvtec.py as below: 
```
if split:
        if split==Split.TRAIN:
            samples = samples[samples.split == split].reset_index(drop=True).sample(n=1)
            print(f"num of data {samples.ndim}")
        else:
            samples = samples[samples.split == split].reset_index(drop=True)
```
But during training, pixel F1 score kept 0 and other metrics became very low. When I tried to output results of PADiM, it shows all predictions are nan value. I'm confused because other papers reported one-shot results of PADiM. Is this a problem of algorithm or a bug in codes?

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

1. using github version of anomalib
2. modify mvtec.py as mentioned before
3. run PADiM train with wide_resnet50 as backbone
4. output results of model

### OS information

OS information:
these don't matter.
- Any other relevant information: I have added several metrics and functions, none of them matters with original model

### Expected behavior

Results of model would be all nan.

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: zipper
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - Accuracy
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
testing on category zipper
[2023-10-18 18:55:05,368] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer.
OpenVINO is not installed. Please install OpenVINO to use OpenVINOInferencer.
/home/m/ysh/other_works/anomalib/tools/anomalib/config/config.py:280: UserWarning: config.project.unique_dir is set to False. This does not ensure that your results will be written in an empty directory and you may overwrite files.
  warn(
Global seed set to 42
/home/m/ysh/conda_env/minigpt4/lib/python3.9/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
FeatureExtractor is deprecated. Use TimmFeatureExtractor instead. Both FeatureExtractor and TimmFeatureExtractor will be removed in a future release.
/home/m/ysh/other_works/anomalib/tools/anomalib/utils/callbacks/__init__.py:153: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
/home/m/ysh/conda_env/minigpt4/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:55: LightningDeprecationWarning: Setting `Trainer(resume_from_checkpoint=)` is deprecated in v1.5 and will be removed in v2.0. Please pass `Trainer.fit(ckpt_path=)` directly instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
You are using a CUDA device ('NVIDIA A800 80GB PCIe') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/home/m/ysh/conda_env/minigpt4/lib/python3.9/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (TMAcc). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.

  warnings.warn(*args, **kwargs)
/home/m/ysh/conda_env/minigpt4/lib/python3.9/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
/home/m/ysh/conda_env/minigpt4/lib/python3.9/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [2]
num of data 2
Testing DataLoader 0:   0%|          | 0/5 [00:00<?, ?it/s]/home/m/ysh/other_works/anomalib/tools/anomalib/post_processing/post_process.py:99: RuntimeWarning: invalid value encountered in cast
  anomaly_map = anomaly_map.astype(np.uint8)
Testing DataLoader 0: 100%|██████████| 5/5 [00:24<00:00,  4.81s/it]torch.Size([151])
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan], device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1], device='cuda:0', dtype=torch.int32)
tensor([0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119,
        0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119, 0.2119])
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan], device='cuda:0')
Testing DataLoader 0: 100%|██████████| 5/5 [00:24<00:00,  4.87s/it]
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        image_AUROC        │    0.5840336680412292     │
│        image_TMAcc        │    0.21192052960395813    │
│       image_TopAcc        │    0.21192052960395813    │
│        pixel_AUROC        │    0.4931238889694214     │
│       pixel_F1Score       │            0.0            │
└───────────────────────────┴───────────────────────────┘
test finished

I pasted one class because all is too much, but all classes output nan values in this case.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
