### ISSUE TITLE
[Task]: How to calculate accuracy ACC

### ISSUE THREAD

**Issue by FudaMingdaXsc** [openvinotoolkit/anomalib#1504]
### What is the motivation for this task?

When I run experiments, I need to calculate the accuracy ACC at the image level. Because the F1 score and accuracy ACC are generally required at the same time in the experiment. It is a pity that this project does not have this parameter. 

### Describe the solution you'd like

 How do I increase this parameter?

**Comment by blaz-r** [comment]
Hello. Anomalib also supports metrics from Torchmetrics. You can add Accuracy to config:
```yaml
...
metrics:
  image:
    - F1Score
    - Accuracy
  pixel:
    - F1Score
    - Accuracy
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null
...
```
