### ISSUE TITLE
[Bug]: python tools/train.py --model efficient_ad  --config ****.yaml #not train myself data 

### ISSUE THREAD

**Issue by dugushiyu** [openvinotoolkit/anomalib#1508]
### Describe the bug

[Bug]: python tools/train.py --model efficient_ad  --config ****.yaml #not train myself data 

### Dataset

Folder

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

[Bug]: python tools/train.py --model efficient_ad  --config ****.yaml #not train myself data 

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.10]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

no

### Pip/GitHub

pip

### Configuration YAML

```yaml
dataset:
  name: tube               # 数据集的名字，如MVTec等，这个不重要
  format: folder
  path: ./datasets/img_192 # 自制数据集路径
  normal_dir: normal       # 自制数据集正样本子文件夹
  abnormal_dir: abnormal   # 自制数据集负样本子文件夹
  mask_dir: null           # 二值掩膜路径，自制数据集一般没有，填null
  normal_test_dir: null # name of the folder containing normal test images.
  task: classification # classification or segmentation
  extensions: null
```

### Logs

```shell
it to load network imagenette2.zar

lightning_model.py imagenet_dir=path("./datasets/imagenette")
to
imagenet_dir=path("./datasets/img_192")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
