### ISSUE TITLE
🐞Path is outside the allowed directory when using Docker container

### ISSUE THREAD

**Issue by phcarval** [openvinotoolkit/anomalib#1719]
### Describe the bug

See also: https://github.com/openvinotoolkit/anomalib/issues/1688
Hello,
I have some trouble getting Anomalib to work while using a Docker container, since it uses `validate_path()`. By default, while using the MVTec dataset, Anomalib checks for the path to be in `Path.home()`, which is `/home/user`, while Docker usually works in `/workspaces`.

Furthermore, I have another configuration where my data is not stored in my home folder. I expect that this will break as well. 

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

Install anomalib by cloning the repo
Build the container in VSCode
Launch the command `anomalib train --model Patchcore --data anomalib.data.MVTec`

### OS information

N/A

### Expected behavior

Checks that the path is in a list of user-defined approved paths?

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
class_path: anomalib.data.MVTec
init_args:
  root: ./datasets/MVTec
  category: bottle
  image_size: [256, 256]
  center_crop: null
  normalization: imagenet
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  task: SEGMENTATION
  transform_config_train: null
  transform_config_eval: null
  test_split_mode: FROM_DIR
  test_split_ratio: 0.2
  val_split_mode: SAME_AS_TEST
  val_split_ratio: 0.5
  seed: null
```

### Logs

```shell
Unable to paste the logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
