### ISSUE TITLE
[Bug]: Albumentations `TypeError: load() got an unexpected keyword argument 'filepath'`

### ISSUE THREAD

**Issue by CarlosNacher** [openvinotoolkit/anomalib#1801]
### Describe the bug

When trying to `load` Albumentation transforms from `.yaml` it fails because tries to pass `filepath` argument to `load` function, but the correct way is with `filepath_or_buffer` or even better, without any keyword argument (more stable if future changes of Albumentations I think).

### Dataset

MVTec

### Model

Reverse Distillation

### Steps to reproduce the behavior

Try to set any path to a `.yaml` file in the `config.yaml` file of a model (in `train_transforms` or `eval_transforms` args)

### OS information

OS information:
- OS: Microsoft Windows 11 Home
- Python version: 3.10.13
- Anomalib version: 1.0.0dev
- PyTorch version: 2.2.0+cu121
- CUDA/cuDNN version: 12.4
- GPU models and configuration: 1x GeForce RTX 3090
- Any other relevant information: None

### Expected behavior

Not raising error. Proposed solution: change `A.load(filepath=config, data_format="yaml")` with `A.loadconfig, data_format="yaml")` in all lines it appears.

### Pip/GitHub

pip

### What version/branch did you use?

1.0.0dev

### Configuration YAML

```yaml
dataset:
  name: experiment_name
  format: mvtec
  path: ../data/external/MVTec
  category: my_own_category
  task: segmentation
  train_batch_size: 1
  eval_batch_size: 8
  num_workers: 16
  image_size: # dimensions to which images are resized (mandatory)
    - 1408 # 1408x896 are the sizes most similar to 1440x930 (keep aspect ratio of original image) that: 1) are divisible by 2 at least 6 times (for convolution downsamplings compataibility) and 2) fit in memory of GPU RTX 3090 24GB 
    - 896
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: none # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: ./train_data_augmentation.yaml
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
  name: reverse_distillation
  lr: 0.005
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  beta1: 0.5
  beta2: 0.999
  normalization_method: min_max # options: [null, min_max, cdf]
  anomaly_map_mode: add # options: [add, multiply]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ../results

logging:
  logger: [wandb] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: False # Logs the model graph to respective logger.

optimization:
  export_mode: torch # options: torch, onnx, openvino
# PL Trainer Args. Don't add extra parameter here.
trainer:
  resume_from_checkpoint: ../results/reverse_distillation/mymodel/run/weights/lightning/model.ckpt
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 500
  min_epochs: null
  max_steps: 70000
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[63], line 8
      5 CONFIG_PATH = "./config.yaml"
      6 config = get_configurable_parameters(config_path=CONFIG_PATH)
----> 8 datamodule = get_datamodule(config)
      9 datamodule.prepare_data()  # Downloads the dataset if it's not in the specified `root` directory
     10 datamodule.setup()

File c:\Users\LENOVO\anaconda3\envs\ia_model_temp\lib\site-packages\anomalib\data\__init__.py:62, in get_datamodule(config)
     59     center_crop = (center_crop[0], center_crop[1])
     61 if config.dataset.format.lower() == DataFormat.MVTEC:
---> 62     datamodule = MVTec(
     63         root=config.dataset.path,
     64         category=config.dataset.category,
     65         image_size=(config.dataset.image_size[0], config.dataset.image_size[1]),
     66         center_crop=center_crop,
     67         normalization=config.dataset.normalization,
     68         train_batch_size=config.dataset.train_batch_size,
     69         eval_batch_size=config.dataset.eval_batch_size,
     70         num_workers=config.dataset.num_workers,
     71         task=config.dataset.task,
     72         transform_config_train=config.dataset.transform_config.train,
     73         transform_config_eval=config.dataset.transform_config.eval,
     74         test_split_mode=config.dataset.test_split_mode,
     75         test_split_ratio=config.dataset.test_split_ratio,
     76         val_split_mode=config.dataset.val_split_mode,
     77         val_split_ratio=config.dataset.val_split_ratio,
     78     )
     79 elif config.dataset.format.lower() == DataFormat.MVTEC_3D:
     80     datamodule = MVTec3D(
     81         root=config.dataset.path,
     82         category=config.dataset.category,
   (...)
     95         val_split_ratio=config.dataset.val_split_ratio,
     96     )

File c:\Users\LENOVO\anaconda3\envs\ia_model_temp\lib\site-packages\anomalib\data\mvtec.py:260, in MVTec.__init__(self, root, category, image_size, center_crop, normalization, train_batch_size, eval_batch_size, num_workers, task, transform_config_train, transform_config_eval, test_split_mode, test_split_ratio, val_split_mode, val_split_ratio, seed)
    257 self.root = Path(root)
    258 self.category = Path(category)
--> 260 transform_train = get_transforms(
    261     config=transform_config_train,
    262     image_size=image_size,
    263     center_crop=center_crop,
    264     normalization=InputNormalizationMethod(normalization),
    265 )
    266 transform_eval = get_transforms(
    267     config=transform_config_eval,
    268     image_size=image_size,
    269     center_crop=center_crop,
    270     normalization=InputNormalizationMethod(normalization),
    271 )
    273 self.train_data = MVTecDataset(
    274     task=task, transform=transform_train, split=Split.TRAIN, root=root, category=category
    275 )

File c:\Users\LENOVO\anaconda3\envs\ia_model_temp\lib\site-packages\anomalib\data\utils\transform.py:109, in get_transforms(config, image_size, center_crop, normalization, to_tensor)
    107 elif isinstance(config, str):
    108     logger.info("Reading transforms from Albumentations config file: %s.", config)
--> 109     transforms = A.load(filepath=config, data_format="yaml")
    110 elif isinstance(config, A.Compose):
    111     logger.info("Transforms loaded from Albumentations Compose object")

TypeError: load() got an unexpected keyword argument 'filepath'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
