### ISSUE TITLE
[Bug]: Evaluation results mismatch when training Patchcore on MVTec using default config

### ISSUE THREAD

**Issue by 1713mz** [openvinotoolkit/anomalib#1882]
### Describe the bug

I was trying to validate the results of Patchcore model on MVTec, however my results differ from the listed ones under "source/anomalib/models/image/patchcore". 

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

I used the following CLI command for training: "anomalib train --seed_everything 42   --model Patchcore --metrics.image AUROC --metrics.pixel AUROC --data anomalib.data.MVTec --data.category capsule"

### OS information

OS information:
- OS: Windows 10
- Python version: 3.10.13
- Anomalib version: V1.0
- PyTorch version: 2.0.0
- CUDA/cuDNN version: 11.7
- GPU models and configuration: GeForce RTX 3060

### Expected behavior

Expected: image-level AUC 0.982 pixel-level AUC 0.988 (for class capsule) image-level AUC 0.924 pixel-level AUC 0.980 (for class pill) 
My results: image-level AUC 0.992 pixel-level AUC 0.990 (for class capsule) image-level AUC 0.944 pixel-level AUC 0.980 (for class pill) 

### Pip/GitHub

pip

### Configuration YAML

```yaml
config: null
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: results_test\patchcore\mvtec\capsule
normalization:
  normalization_method: MIN_MAX
visualization:
  image_save_path: results_test\patchcore\mvtec\capsule\images
  mode: FULL
  inputs_are_normalized: true
  show_images: false
  log_images: true
  save_images: true
task: SEGMENTATION
metrics:
  image: AUROC
  pixel: AUROC
  threshold:
    class_path: anomalib.metrics.F1AdaptiveThreshold
    init_args:
      default_value: 0.5
      pos_label: null
      task: null
      thresholds: null
      num_labels: null
      ignore_index: null
      validate_args: true
      compute_on_cpu: false
      dist_sync_on_step: false
      sync_on_compute: true
logging:
  log_graph: false
results_dir:
  path: results_test\patchcore\mvtec\capsule
  unique: false
ckpt_path: null
model:
  class_path: anomalib.models.Patchcore
  init_args:
    input_size:
    - 256
    - 256
    backbone: wide_resnet50_2
    layers:
    - layer2
    - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
data:
  class_path: anomalib.data.MVTec
  init_args:
    root: datasets\MVTec
    category: capsule
    image_size:
    - 256
    - 256
    center_crop: null
    normalization: IMAGENET
    train_batch_size: 32
    eval_batch_size: 32
    num_workers: 8
    task: SEGMENTATION
    transform_config_train: null
    transform_config_eval: null
    test_split_mode: FROM_DIR
    test_split_ratio: 0.2
    val_split_mode: SAME_AS_TEST
    val_split_ratio: 0.5
    seed: null
```

### Logs

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
