### ISSUE TITLE
[Bug]: Validation Score goes to 0 while in the middle of training

### ISSUE THREAD

**Issue by papago2355** [openvinotoolkit/anomalib#1942]
### Describe the bug

Hi
I recently use a custom dataset with EfficientAD for classification task.
It works well so far, but sometimes pltrainer validation score shows 0.
At first I thought this was just an error of my pc but it happens regulary and have no clue why it happens.
Usually it happens when I set epochs higher than 200, but sometimes it just happened when I just set it 50.

I use a high resolution image dataset(1600X3200), and resize it to 800X1600 while in training.
I use Folder Dataset and it has 400 normal sample images, 300 abnormal sample images and 50 test normal images.
Can anyone have any idea why this happened?
![image](https://github.com/openvinotoolkit/anomalib/assets/68721273/a92e7d20-a3e1-46ac-8c6e-f54e0c8a43be)

ps. Seems like F1-Score early stopping is not working at all. Am I doing something wrong at my config?
### Dataset

Folder

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

Using EfficientAD-S with a custom dataset
Set Early stopping for F1-Score
Set Epochs 200

### OS information

OS information:
- OS: windows11
- Python version: 3.8
- Anomalib version: 0.70

### Expected behavior

expect F1-Score not to go 0 suddenly.

### Pip/GitHub

pip

### What version/branch did you use?

0.7

### Configuration YAML

```yaml
dataset:
  name: belt_test
  root: ./datasets
  format: folder
  task: classification
  normal_dir : belts/march_new/good_conv/180
  abnormal_dir : belts/march_new/bad_conv/180
  normal_test_dir : belts/march_new/test_conv/180
  mask_dir : null
  train_batch_size: 1
  eval_batch_size: 16
  extensions : null
  num_workers: 8
  image_size: [700,1280] # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: none # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
  name: efficient_ad
  teacher_out_channels: 384
  model_size: small # options: [small, medium]
  lr: 0.0001
  weight_decay: 0.00001
  padding: false
  pad_maps: true # relevant for "padding: false", see EfficientAd in lightning_model.py
  # generic params
  early_stopping:
    patience: 3
    metric: image_F1Score
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: False # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: simple # options: ["full", "simple"]

project:
  seed: 42
  path: ./test_4_2_180_714

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: torch # options: torch, onnx, openvino
# PL Trainer Args. Don't add extra parameter here.
trainer:
    enable_checkpointing: true
    default_root_dir: null
    gradient_clip_val: 0
    gradient_clip_algorithm: norm
    num_nodes: 1
    devices: 1
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    accumulate_grad_batches: 1
    max_epochs: 50 # 200
    min_epochs: null
    max_steps: 70000 #70000
    min_steps: null
    max_time: null
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    log_every_n_steps: 2 # 50
    accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
    strategy: null
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    num_sanity_val_steps: 0
    profiler: null
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    plugins: null
    move_metrics_to_cpu: false
```

### Logs

```shell
Since I saw this at pltrainer without any logs, I can't post any logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
