### ISSUE TITLE
Use `move_metrics_to_cpu` from `Trainer` to move metric computation to CPU

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#202]
**Is your feature request related to a problem? Please describe.**
  - Moving metric computation to cpu is currently not working properly.

**Describe the solution you'd like**
  - We could instead use `move_metrics_to_cpu` in `Trainer` in `config.yaml` file. This way, PL would handle all the device assignments.

```yaml
# PL Trainer Args. Don't add extra parameter here.
trainer:
  ...
  move_metrics_to_cpu: true
  ...
```
- Might impact #110
