### ISSUE TITLE
[Bug]: Wrong keys in data configs

### ISSUE THREAD

**Issue by abc-125** [openvinotoolkit/anomalib#2031]
### Describe the bug

When I try to run training using config files for any model and dataset, the training fails because of the wrong keys in data configs.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

1. Install anomalib with 
<code>git clone https://github.com/openvinotoolkit/anomalib.git<br>
cd anomalib<br>
pip install -e .<br></code>
2. Run command `anomalib train -c configs/model/patchcore.yaml --data configs/data/mvtec.yaml` (it can be any other model and  another dataset)

### OS information

PyTorch 2.1.2+cu118

### Expected behavior

Start training :)

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
class_path: anomalib.data.MVTec
init_args:
  root: ./datasets/MVTec
  category: bottle
  image_size: [256, 256]
  center_crop: null
  normalization: imagenet
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  task: segmentation
  transform_config_train: null
  transform_config_eval: null
  test_split_mode: from_dir
  test_split_ratio: 0.2
  val_split_mode: same_as_test
  val_split_ratio: 0.5
  seed: null
```

### Logs

```shell
anomalib train -c configs/model/patchcore.yaml --data configs/data/mvtec.yaml
Usage: anomalib [-h] [-c CONFIG] [--print_config [=flags]] {install,fit,validate,test,train,predict,export} ...
error: Parser key "data":
  Problem with given class_path 'anomalib.data.MVTec':
    Validation failed: No action for key "center_crop" to check its value.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
