### ISSUE TITLE
[Bug]: How to solve this problem self.image_threshold = AnomalyScoreThreshold().cpu()

### ISSUE THREAD

**Issue by baoyuchen** [openvinotoolkit/anomalib#2146]
### Describe the bug

  File "D:\workplace2\anomalib-0.7.0\src\anomalib\models\components\base\anomaly_module.py", line 48, in __init__
    self.image_threshold = AnomalyScoreThreshold().cpu()
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
I'm getting this error with version 0.7, what should I do to fix this?
<img width="1010" alt="dbf6c63084e0913cccc3167f2c60a38" src="https://github.com/openvinotoolkit/anomalib/assets/43003320/385b1c83-f967-4a7e-91b8-6f4ff885b26f">
<img width="1010" alt="dbf6c63084e0913cccc3167f2c60a38" src="https://github.com/openvinotoolkit/anomalib/assets/43003320/e2dc79c0-7ba7-4de2-919d-e8b8fa4a11a3">

My configuration file is
dataset:
  name: mvtec
  format: mvtec
  path: D:/workplace2/mvtec/
  category: bottle
  task: segmentation
  train_batch_size: 1
  eval_batch_size: 1
  inference_batch_size: 1
  num_workers: 0
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
  name: cflow
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
    - layer4
  decoder: freia-cflow
  condition_vector: 128
  coupling_blocks: 8
  clamp_alpha: 1.9
  fiber_batch_size: 64
  permute_soft: false
  lr: 0.0001
  early_stopping:
    patience: 2
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: gpu # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle

### Dataset

Folder

### Model

CFlow

### Steps to reproduce the behavior

1TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

What's the solution?
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'

### Screenshots

What's the solution?
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'

### Pip/GitHub

pip

### What version/branch did you use?

0.7.0

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: D:/workplace2/mvtec/
  category: bottle
  task: segmentation
  train_batch_size: 1
  eval_batch_size: 1
  inference_batch_size: 1
  num_workers: 0
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
  name: cflow
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
    - layer4
  decoder: freia-cflow
  condition_vector: 128
  coupling_blocks: 8
  clamp_alpha: 1.9
  fiber_batch_size: 64
  permute_soft: false
  lr: 0.0001
  early_stopping:
    patience: 2
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: gpu # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
What's the solution?
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
TypeError: PrecisionRecallCurve.__new__() missing 1 required positional argument: 'task'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
