### ISSUE TITLE
[Bug]: Tile Pipeline yaml configuration class_path Class Folder not supported

### ISSUE THREAD

**Issue by federicocaccialanzaabb** [openvinotoolkit/anomalib#2409]
### Describe the bug

I was trying the new tiling pipeline of the version 1.2.0 and when trying to use a custom dataset and setting class path as anomalib.data.Folder and not as mvtec I was getting an error because of category, because there is no category in [Folder class](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/data/image/folder.py) Category must be passed to the yaml file if not I am getting an error here in the creation of the ensemble environment [category](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/pipelines/tiled_ensemble/components/utils/ensemble_engine.py). My quick fix was to copy the code and change category with name (which is a must in Folder class and can function as the category in the ensemble engine).

Also in the docs, in the [tile pipeline](https://anomalib.readthedocs.io/en/latest/markdown/guides/how_to/pipelines/tiled_ensemble.html) the accelerator was set as gpu while for me only cuda works: probably for this [here](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/pipelines/tiled_ensemble/train_pipeline.py)

### Dataset

Other (please specify in the text field below)

### Model

PADiM

### Steps to reproduce the behavior

just following the how to guide with a custom dataset

### OS information

Python 3.10.12
anomalib 1.2.0

### Expected behavior

I think that the pipeline should be able to get both folder and mvtec as an input in class path in the yaml configuration file and work accordingly

### Pip/GitHub

pip

### Configuration YAML

```yaml
seed: 42
accelerator: "gpu"  # needed to be changed to cuda
default_root_dir: "results"
tiling:
  tile_size: [256, 256]
  stride: 256

normalization_stage: image 
thresholding:
  method: F1AdaptiveThreshold 
  stage: image 

data:
  class_path: anomalib.data.MVTec # error when I changed to anomalib.data.Folder
  init_args: ...

TrainModels:
    class_path: Padim
```

### Logs

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
