### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by andriy-onufriyenko** [openvinotoolkit/anomalib#243]
I want to train CFLOW model on custom dataset.

`config.yaml`
```
dataset:
  name: Concrete_Crack #options: [mvtec, btech, folder, concrete_crack]
  format: folder # mvtec
  path: ./datasets/Concrete_Crack/ # ./datasets/MVTec
  normal_dir: 'train/Negative'
  abnormal_dir: 'test/Positive'
  normal_test_dir: 'test/Negative'
  task: segmentation
  mask: ./datasets/Concrete_Crack/ground_truth/
  extensions: '.jpg'
  split_ratio: 0.1
  seed: 0
#  category: bottle
  image_size: 227
  train_batch_size: 8 # 16
  test_batch_size: 8 # 16
  inference_batch_size: 8 # 16
  fiber_batch_size: 64
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
```
My dataset have the same structure like MVTec
![image](https://user-images.githubusercontent.com/103642699/164267180-6ffd544c-78c5-452d-a034-ab3f60237869.png)

**To Reproduce**
`python3 tools/train.py --model_config_path anomalib/models/cflow/config.yaml
`

When I start the training, I get an error:

```
File "/home/Projects/Anomalib/anomalib/anomalib/data/folder.py", line 282, in __getitem__
    mask = cv2.imread(mask_path, flags=0) / 255.0
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by julien-blanchon** [comment]
`cv2.imread(mask_path, flags=0)` may return None. Try using only absolute path in your config file (and in particular for mask path)

**Comment by andriy-onufriyenko** [comment]
> Try using only absolute path in your config file (and in particular for mask path)

Got:
```
File "/home/Projects/Anomalib/anomalib/anomalib/data/folder.py", line 80, in _prepare_files_labels
    raise RuntimeError(f"Found 0 {path_type} images in {path}")
RuntimeError: Found 0 normal images in /datasets/Concrete_Crack/train/Negative
```

**Comment by djdameln** [comment]
@andriy-onufriyenko Did you specify the image extension correctly? I can replicate your error by passing `extensions: '.jpg'` in the config and having `.png` images in the dataset folder.

**Comment by samet-akcay** [comment]
@andriy-onufriyenko, I've created a PR #249 to address your issue. You could use [this branch](https://github.com/openvinotoolkit/anomalib/tree/hotfix/sa/mask_filenames_in_folder_dataset) to test it for now.

I've used the following configuration, and successfully trained the model.

```yaml
dataset:
  name: Concrete_Crack #options: [mvtec, btech, folder, concrete_crack]
  format: folder # mvtec
  path: ./datasets/Concrete_Crack/ # ./datasets/MVTec
  normal_dir: "train/Negative"
  abnormal_dir: "test/Positive"
  normal_test_dir: "test/Negative"
  task: segmentation
  mask: ./datasets/Concrete_Crack/ground_truth/Positive
  extensions: ".jpg"
  split_ratio: 0.1
  seed: 0
  image_size: 227
  train_batch_size: 8 # 16
  test_batch_size: 8 # 16
  inference_batch_size: 8 # 16
  fiber_batch_size: 64
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```
