### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by Septembit** [openvinotoolkit/anomalib#2510]
### Describe the bug

when I tried to train a fastflow model by config file, I got this error.
the version is anomalib==2.0.0b2

### Dataset

Folder

### Model

FastFlow

### Steps to reproduce the behavior

` anomalib fit --config ./config.yaml`

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

NG

### Screenshots

<img width="1094" alt="Image" src="https://github.com/user-attachments/assets/3e9c5e79-41ab-40b4-91b6-99999448694d" />

`

### Pip/GitHub

pip

### What version/branch did you use?

2.0.0b2

### Configuration YAML

```yaml
# anomalib==2.0.0b2
seed_everything: true

model:
  class_path: anomalib.models.Fastflow
  init_args:
    backbone: resnet18
    pre_trained: true
    flow_steps: 8
    conv3x3_only: false
    hidden_ratio: 1.0

trainer:
  max_epochs: 500
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 3
        monitor: pixel_AUROC
        mode: max
data:
  class_path: anomalib.data.Folder
  init_args:
    name: bottle_0528
    normal_dir: ok
    root: data/bottle-bottom-dataset
    abnormal_dir: ng
    normal_test_dir: null
    mask_dir: null
    normal_split_ratio: 0.2
    extensions: null
    train_batch_size: 1
    eval_batch_size: 1
    num_workers: 0
    train_augmentations: null
    val_augmentations: null
    test_augmentations: null
    augmentations: null
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.2
    seed: null
logging:
  log_graph: false
default_root_dir: results
ckpt_path: null
```

### Logs

```shell
NG
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by alexriedel1** [comment]
If you don't provide a mask dir `mask_dir: null` of ground truth masks of anomalous samples, the trainer assumes you want to perform a classifaction task instead of an segmentation task. In an classification task, you cannot calculate pixel metrics (such as pixel_AUROC)

**Comment by Septembit** [comment]
@alexriedel1 
Thanks for your reply, I tried to change the pixel_AUROC to image_AUROC in trainer filed. But I still meet this error.


```
# anomalib==2.0.0b2
seed_everything: true

model:
  class_path: anomalib.models.Fastflow
  init_args:
    backbone: resnet18
    pre_trained: true
    flow_steps: 8
    conv3x3_only: false
    hidden_ratio: 1.0

trainer:
  max_epochs: 500
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 3
        monitor: image_AUROC
        mode: max
data:
  class_path: anomalib.data.Folder
  init_args:
    name: bottle_0528
    normal_dir: ok
    root: data/bottle-bottom-dataset
    abnormal_dir: ng
    normal_test_dir: null
    mask_dir: null
    normal_split_ratio: 0.2
    extensions: null
    train_batch_size: 64
    eval_batch_size: 64
    num_workers: 0
    train_augmentations: null
    val_augmentations: null
    test_augmentations: null
    augmentations: null
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.2
    seed: null
logging:
  log_graph: false
default_root_dir: results
ckpt_path: null
```
