### ISSUE TITLE
Inference for OpenVINO 

### ISSUE THREAD

**Issue by ZeynepRuveyda** [openvinotoolkit/anomalib#295]
Heyy,
I am trying to do inference with OpenVINO.
 ' If the path points to an ONNX graph (.onnx) or OpenVINO IR (.bin or .xml), inference will run in OpenVINO.' according to this explanation ,I changed the path as .onnx. But I got the opset_version error. Normally the default value is 9. But my code advice the value is 11. When I am changing the opset value 9 to 11, It did not support. Do I need to stay with .onnx or change as .bin and .xml? Do you have any sample or solution for this issue?

Pytorch version : 1.11.0

Thanks in advance,

**Comment by ashwinvaidya17** [comment]
@ZeynepRuveyda Which model are you trying to run and what's the version of OpenVINO on your system?

**Comment by ZeynepRuveyda** [comment]
> @ZeynepRuveyda Which model are you trying to run and what's the version of OpenVINO on your system?
Hi @ashwinvaidya17 
openvino version : 2021.4.2

**Comment by ashwinvaidya17** [comment]
Are you passing the meta_data json file to the inference.py?

**Comment by ZeynepRuveyda** [comment]
Hi @ashwinvaidya17 , Apperently not.  We prepare the our dataset like MVTech format ground_truth,test,train. I dont have the .json file in there. Do I need to export my annotations as coco (.json) format? Also, I could not see the samples for openvino inference inside of your anomalib files and documentations. Maybe you can support one sample with MVTech dataset. If there is can you provide me?

Thanks in advance,
Zeynep

**Comment by ashwinvaidya17** [comment]
@ZeynepRuveyda 
Here are the important sections of the config file I am using to test on MVTec on the `development` branch
```yaml
dataset:
  name: mvtec #options: [mvtec, btech, folder]
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 36
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

optimization:
  openvino:
    apply: true

# PL Trainer Args. Don't add extra parameter here.
trainer:
  devices: 1
```

You should see a folder like this in results
![image](https://user-images.githubusercontent.com/17232914/167405165-51c59e78-d49e-4e74-bb43-57986262c3f3.png)

Then, run inference like this
```bash
python tools/inference.py \
    --config  \
    anomalib/models/padim/config.yaml  \
    --weight_path  \
    results/padim/mvtec/bottle/openvino/openvino_model.xml \
    --meta_data \
    results/padim/mvtec/bottle/openvino/meta_data.json \
    --image_path  \
    datasets/MVTec/bottle/test/broken_large/000.png \
 --save_path ./results --overlay_mask true
```

It produces an output like this
![image](https://user-images.githubusercontent.com/17232914/167405766-912e7c6e-d75d-48f5-9f9d-7b0b8a1a8f54.png)
