### ISSUE TITLE
Set different height and weight for custom model

### ISSUE THREAD

**Issue by Nayan-sse-tggs** [openvinotoolkit/anomalib#311]
How to train a custom model with different height and weight? Let's say our input image size height is 1088 and weight is 4096, if I update custom model config file it only takes one parameter as input and send it as same height and weight to network if I am not mistaken. How do I update different sizes in config file for custom model?

If I update my `config.yaml` file given below, if gives TypeError but works fine with single parameter.
```
image_size: 1088, 4096  # Error (height:1088, w:4096): TypeError: new(): invalid data type 'str'
tiling:
  apply: true
  tile_size: 16
  stride: null
  remove_border_count: 0
  use_random_tiling: False
  random_tile_count: 4
```
