### ISSUE TITLE
Anomalib CLI Improvements - Update `metrics` and create `post_processing` section in the `config` file.

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#384]
The new Anomalib CLI has `threshold` and `normalization_method` parameters in the `metrics` section. However, this may not be intuitive. Instead, it would be better to create a `post_processing` to store these parameters.

In addition, `image_metric_names` and `pixel_metric_names` are a bit verbose, especially for the API version. Instead, those could be renamed as `image_metrics` and `pixel_metrics`, respectively.

Overall, the updated config file would be something like:

```yaml
.
.
.
metrics:
  image_metrics:
    - F1Score
    - AUROC
  pixel_metrics:
    - F1Score
    - AUROC

post_processing:
  adaptive_threshold: true
  default_image_threshold: null
  default_pixel_threshold: null
  normalization_method: min_max

visualization:
  task: segmentation
  log_images_to:
    - local
  inputs_are_normalized: true
.
.
.
```

- [ ] Update the metrics_names parameters
- [ ] Assign default values to metrics_names
- [ ] Move threshold and normalization_method parameters to post_processing section.
