### ISSUE TITLE
pixel metrics calculation process bugs

### ISSUE THREAD

**Issue by MacavityT** [openvinotoolkit/anomalib#405]
Once I tried to get pixel metrics like "precision" and "recall", so I set the config in .yaml file as following:
```
metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - Precision
    - F1Score
    - Recall
  threshold:
    image_default: 3
    pixel_default: 15
    adaptive: false
```
But finally I got just "precision" value while the "f1 score" and "recall" as 0.0000

So I changed the code in anomalib/utils/metrics/collection.py as following:
```
    def update(self, *args, **kwargs) -> None:
        """Add data to the metrics."""
    
        # super().update(*args, **kwargs)  # remove this line
        # my addition
        for metric in self.values():
            if callable(getattr(metric, 'update')):
                getattr(metric, 'update')(*args, **kwargs)
        ###

        self._update_called = True
```
Then I got correct results.
