### ISSUE TITLE
Is possible to train only  normal_dir on custom dataset?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [openvinotoolkit/anomalib#464]
https://github.com/openvinotoolkit/anomalib#custom-dataset
 ```
dataset:
  name: <name-of-the-dataset>
  format: folder
  path: <path/to/folder/dataset>
  normal_dir: normal # name of the folder containing normal images.
  abnormal_dir: null # name of the folder containing abnormal images.
  normal_test_dir: null # name of the folder containing normal test images.
  task: segmentation # classification or segmentation
  mask: <path/to/mask/annotations> #optional
  extensions: null
  split_ratio: 0.2  # ratio of the normal images that will be used to create a test split
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```
If someone gives only normal images, it means I have only normal_dir and would like to do train.py with only normal images. And after training, I will provide this model to them to predict with their dataset. Is it possible to do it? 
When I try to set 
```
normal_dir: normal
abnormal: null
```
then it didn't work. 

When I read the notebook for MVTec
https://github.com/openvinotoolkit/anomalib/blob/development/notebooks/100_datamodules/102_mvtec.ipynb
they trained only train/ folder and testing in separated test/ folder. So I think in custom data we could also do the same. Am I wrong thinking?
