### ISSUE TITLE
Convert `adaptive_threshold` to `Enum` in configs

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#635]
Currently the threshold settings are as follows:

```yaml
metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    image_default: 3
    pixel_default: 3
    adaptive: true
```

It would be more logical to convert `adaptive` to `method` which would be stored as `Enum`.
