### ISSUE TITLE
`anomalib.data.folder.Folder` is not properly adapting the `mask_dir` arg

### ISSUE THREAD

**Issue by jpcbertoldo** [openvinotoolkit/anomalib#659]
**Describe the bug**

In `anomalib/data/folder.py`, method `Folder.__init__()`.

There are 4 directory args expected to be relative to the arg `root`. One of them (`mask_dir`) does not get the root properly pre-appended.

![image](https://user-images.githubusercontent.com/24547377/199126975-477a8ed1-4116-4f57-bd80-ba561c2c7d27.png)

Because the function `make_dataset()` will deduce the mask file names from the images, the code does not realize that the dir is wrong until one tries to eval the model and the image loading breaks with file not found.

**To Reproduce**

I used `tools/train` with this dataset config

```yaml
dataset:
  name: loreal-rhe
  format: folder
  path: data/cuda/datasets/mydataset
  normal_dir: train/normal/images
  abnormal_dir: test/anomalous/images
  normal_test_dir: test/normal/images
  task: segmentation  # classification or segmentation
  mask: test/anomalous/masks
  extensions: .tif
  split_ratio: null  # not necessary bc the test set already has normals
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```

The organization of my files are as expected and can be deduced from the config above.
I'm cutting the report short because I already solved it.
