### ISSUE TITLE
[Bug]: Anomalib Colab Test.ipynb Notebook does not work (RUNTIME ERROR)

### ISSUE THREAD

**Issue by scalers-ai** [openvinotoolkit/anomalib#749]
### Describe the bug

Is this a version compatibility issue?

Anomalib Colab Test.ipynb

<img width="963" alt="image" src="https://user-images.githubusercontent.com/91742529/204906144-fbe35ba5-944a-4baf-9ced-2f000e4d275e.png">

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

1. Follow instructions from GitHub here: https://github.com/openvinotoolkit/anomalib
2. Run the example notebook: Anomalib Colab Test.ipynb on Google Colab
3. Witness and face the situation

### OS information

Google Colab

<img width="331" alt="image" src="https://user-images.githubusercontent.com/91742529/204911716-c3f9e4fb-2f9b-4731-9020-0daf0c5e2b13.png">

### Expected behavior

1. Follow documentation instructions
2. Execute steps in the documentation/Colab notebook
3. Not get unexpected errors

### Screenshots

<img width="818" alt="image" src="https://user-images.githubusercontent.com/91742529/204912357-05da67b5-0a5e-425d-b962-8ad0aee19b3e.png">

### Pip/GitHub

GitHub

### What version/branch did you use?

main

### Configuration YAML

```yaml
# This is the config file for the new Anomalib CLI.
# To use this, run the following command:
# anomalib fit --config ./config/model/padim.yaml
ckpt_path: null
seed_everything: null

data:
  class_path: anomalib.data.MVTec
  init_args:
    root: ./datasets/MVTec
    category: bottle
    image_size: [256, 256]
    train_batch_size: 32
    test_batch_size: 32
    num_workers: 8
    task: segmentation
    transform_config_train: null
    transform_config_val: null
    seed: 0
    create_validation_set: false

model:
  class_path: anomalib.models.Padim
  init_args:
    input_size:
      - 256 # Height
      - 256 # Width
    backbone: resnet18
    pre_trained: true
    layers:
      - layer1
      - layer2
      - layer3

post_processing:
  normalization_method: min_max # <null, min_max, cdf>
  threshold_method: adaptive # options: [adaptive, manual]
  manual_image_threshold: null
  manual_pixel_threshold: null

metrics:
  image_metrics:
    - F1Score
    - AUROC
  pixel_metrics:
    - F1Score
    - AUROC

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: False # log images to the available loggers (if any)
  mode: full # options: ["full", "simple"]

trainer:
  logger: true
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.
```

### Logs

```shell
/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `PrecisionRecallCurve` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.7/dist-packages/anomalib/utils/callbacks/__init__.py:143: UserWarning: Export option: None not found. Defaulting to no model export
  warnings.warn(f"Export option: {config.optimization.export_mode} not found. Defaulting to no model export")
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:52: LightningDeprecationWarning: Setting `Trainer(resume_from_checkpoint=)` is deprecated in v1.5 and will be removed in v1.7. Please pass `Trainer.fit(ckpt_path=)` directly instead.
  "Setting `Trainer(resume_from_checkpoint=)` is deprecated in v1.5 and"
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_test_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(limit_predict_batches=1.0)` was configured so 100% of the batches will be used..
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
Transform configs has not been provided. Images will be normalized using ImageNet statistics.
/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `ROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.7/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Predicting DataLoader 0: 100% 1/1 [00:00<00:00,  2.20it/s]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
