### ISSUE TITLE
[Bug]: AUPRO returns an error when weights are loaded to the model.

### ISSUE THREAD

**Issue by samet-akcay** [openvinotoolkit/anomalib#790]
### Describe the bug

When the model is loaded with weights anomalib returns the following error:

```bash
        if len(error_msgs) > 0:
>           raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
                               self.__class__.__name__, "\n\t".join(error_msgs)))
E           RuntimeError: Error(s) in loading state_dict for CfaLightning:
E               Unexpected key(s) in state_dict: "pixel_metrics.AUPRO.fpr_limit".

../../miniconda3/envs/anomalib/lib/python3.8/site-packages/torch/nn/modules/module.py:1604: RuntimeError
```

### Dataset

MVTec

### Model

N/A

### Steps to reproduce the behavior

1. Use the following config:

```yaml
metrics:
  image:
    - AUROC
  pixel:
    - AUROC
    - AUPRO
```

1. Run the tests via `python -m pytest tests/pre_merge/models/test_model_premerge.py`

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.8.10]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

The tests should pass.

### Pip/GitHub

pip

### What version/branch did you use?

https://github.com/openvinotoolkit/anomalib/tree/feature/model/cfa

### Configuration YAML

```yaml
dataset:
  name: mvtec #options: [mvtec, btech, folder]
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  image_size: 224
  train_batch_size: 4
  test_batch_size: 4
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: cfa
  backbone: wide_resnet50_2
  gamma_c: 1
  gamma_d: 1
  lr: 1e-3
  weight_decay: 5e-4
  amsgrad: true
  early_stopping:
    patience: 5
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - AUROC
  pixel:
    - AUROC
    - AUPRO
  threshold:
    image_default: 0
    pixel_default: 0
    adaptive: true

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 30
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0
```

### Logs

```shell
======================================================================================== FAILURES ========================================================================================
____________________________________________________________________________ TestModel.test_model[cfa-False] _____________________________________________________________________________

self = <tests.pre_merge.models.test_model_premerge.TestModel object at 0x7f7344915cd0>, model_name = 'cfa', nncf = False, category = 'shapes', path = '/tmp/tmp48a71ezu'

    @pytest.mark.parametrize(
        ["model_name", "nncf"],
        [
            ("cfa", False),
            # ("cflow", False),
            # ("dfkde", False),
            # ("dfm", False),
            # ("draem", False),
            # ("fastflow", False),
            # ("ganomaly", False),
            # ("padim", False),
            # ("patchcore", False),
            # ("reverse_distillation", False),
            # ("stfpm", False),
        ],
    )
    @TestDataset(num_train=20, num_test=10)
    def test_model(self, model_name, nncf, category="shapes", path=""):
        """Test the models on only 1 epoch as a sanity check before merge."""
        with tempfile.TemporaryDirectory() as project_path:
            # Train test
            config, datamodule, model, trainer = setup_model_train(
                model_name,
                dataset_path=path,
                project_path=project_path,
                nncf=nncf,
                category=category,
                fast_run=True,
            )
            results = trainer.test(model=model, datamodule=datamodule)[0]
    
            # Test model load
>           model_load_test(config, datamodule, results)

tests/pre_merge/models/test_model_premerge.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/helpers/model.py:145: in model_load_test
    new_results = trainer.test(model=loaded_model, datamodule=datamodule)[0]
../../.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:938: in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
../../.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:723: in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
../../.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:985: in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
../../.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1174: in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
../../.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1493: in _call_setup_hook
    self._call_callback_hooks("setup", stage=fn)
../../.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1636: in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
anomalib/utils/callbacks/model_loader.py:32: in setup
    pl_module.load_state_dict(torch.load(self.weights_path, map_location=pl_module.device)["state_dict"])
anomalib/models/components/base/anomaly_module.py:192: in load_state_dict
    return super().load_state_dict(state_dict, strict=strict)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = CfaLightning(
  (image_threshold): AnomalyScoreThreshold()
  (pixel_threshold): AnomalyScoreThreshold()
  (model): Cfa...(conv2d): Conv2d(1794, 1792, kernel_size=(1, 1), stride=(1, 1))
      )
    )
  )
  (normalization_metrics): MinMax()
)
state_dict = OrderedDict([('model.memory_bank', tensor([[-0.0298, -0.0289, -0.0360,  ..., -0.0266, -0.0017,  0.0025],
        [-0.0...sor([ 0.0138,  0.0205, -0.0092,  ...,  0.0095,  0.0230, -0.0041])), ('pixel_metrics.AUPRO.fpr_limit', tensor(0.3000))])
strict = True

    def load_state_dict(self, state_dict: Mapping[str, Any],
                        strict: bool = True):
        r"""Copies parameters and buffers from :attr:`state_dict` into
        this module and its descendants. If :attr:`strict` is ``True``, then
        the keys of :attr:`state_dict` must exactly match the keys returned
        by this module's :meth:`~torch.nn.Module.state_dict` function.
    
        Args:
            state_dict (dict): a dict containing parameters and
                persistent buffers.
            strict (bool, optional): whether to strictly enforce that the keys
                in :attr:`state_dict` match the keys returned by this module's
                :meth:`~torch.nn.Module.state_dict` function. Default: ``True``
    
        Returns:
            ``NamedTuple`` with ``missing_keys`` and ``unexpected_keys`` fields:
                * **missing_keys** is a list of str containing the missing keys
                * **unexpected_keys** is a list of str containing the unexpected keys
    
        Note:
            If a parameter or buffer is registered as ``None`` and its corresponding key
            exists in :attr:`state_dict`, :meth:`load_state_dict` will raise a
            ``RuntimeError``.
        """
        if not isinstance(state_dict, Mapping):
            raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
    
        missing_keys: List[str] = []
        unexpected_keys: List[str] = []
        error_msgs: List[str] = []
    
        # copy state_dict so _load_from_state_dict can modify it
        metadata = getattr(state_dict, '_metadata', None)
        state_dict = OrderedDict(state_dict)
        if metadata is not None:
            # mypy isn't aware that "_metadata" exists in state_dict
            state_dict._metadata = metadata  # type: ignore[attr-defined]
    
        def load(module, prefix=''):
            local_metadata = {} if metadata is None else metadata.get(prefix[:-1], {})
            module._load_from_state_dict(
                state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
            for name, child in module._modules.items():
                if child is not None:
                    load(child, prefix + name + '.')
    
            # Note that the hook can modify missing_keys and unexpected_keys.
            incompatible_keys = _IncompatibleKeys(missing_keys, unexpected_keys)
            for hook in module._load_state_dict_post_hooks.values():
                out = hook(module, incompatible_keys)
                assert out is None, (
                    "Hooks registered with ``register_load_state_dict_post_hook`` are not"
                    "expected to return new values, if incompatible_keys need to be modified,"
                    "it should be done inplace."
                )
    
        load(self)
        del load
    
        if strict:
            if len(unexpected_keys) > 0:
                error_msgs.insert(
                    0, 'Unexpected key(s) in state_dict: {}. '.format(
                        ', '.join('"{}"'.format(k) for k in unexpected_keys)))
            if len(missing_keys) > 0:
                error_msgs.insert(
                    0, 'Missing key(s) in state_dict: {}. '.format(
                        ', '.join('"{}"'.format(k) for k in missing_keys)))
    
        if len(error_msgs) > 0:
>           raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
                               self.__class__.__name__, "\n\t".join(error_msgs)))
E           RuntimeError: Error(s) in loading state_dict for CfaLightning:
E               Unexpected key(s) in state_dict: "pixel_metrics.AUPRO.fpr_limit".

../../miniconda3/envs/anomalib/lib/python3.8/site-packages/torch/nn/modules/module.py:1604: RuntimeError
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
