### ISSUE TITLE
Correct way to train image without anomaly image

### ISSUE THREAD

**Issue by thanh-repo** [openvinotoolkit/anomalib#799]
Hi, I am interested in ganomaly model to detect anomaly images based on training only normal images.

I have referred to this topic #192 to set threshold to manual. But I am not sure this is the correct way or not.

This is my config data and file structure:
My dataset is named as wallcrack
```
anomalib/
├─ datasets/
│  ├─ wallcrack/
│  │  ├─ good/
│  │  │  ├─ image_0.jpg
│  │  │  ├─ ...
│  │  │  ├─ image_n.jpg
│  │  ├─ bad/
│  │  │  ├─ good_image_also.jpg
```

config.yaml
```
dataset:
  name: folder #options: [mvtec, btech, folder]
  format: folder
  path: ./datasets/wallcrack
  normal_dir: good
  abnormal_dir: bad 
  ...

metrics:
  ...
  threshold:
    method: manual #manual: [adaptive, manual]
    manual_image: 0.5
    manual_pixel: 0.5
```

```
Command: anomalib>python tools/train.py --model ganomaly --config datasets/wallcrack/config.yaml
```

Could anyone please confirm this is the correct way?

Thanks, and best regards!
