### ISSUE TITLE
Can help to see what the problem is

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/anomalib#810]
```
dataset:
  name: <name-of-the-dataset>
  format: folder
  path: <path/to/folder/dataset>
  normal_dir: OK                             # name of the folder containing normal images.
  abnormal_dir: NG                      # name of the folder containing abnormal images.
  normal_test_dir: null # name of the folder containing normal test images.
  task: segmentation # classification or segmentation
  mask: MASK                       #optional
  extensions: null
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 1280
  train_batch_size: 16
  test_batch_size: 16
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```

![11](https://user-images.githubusercontent.com/6490927/209110542-c1b81162-541e-489c-89cc-1faee2cabaea.jpg)
![ng14](https://user-images.githubusercontent.com/6490927/209111049-166676cf-f1f3-4092-9795-651f24d81709.jpg)
![ng11](https://user-images.githubusercontent.com/6490927/209111593-2c4a166b-0f34-477d-af5f-4b98b06bc4a0.jpg)

![image_ROC](https://user-images.githubusercontent.com/6490927/209113475-1d593e66-520a-4573-b260-c6bbb23501fe.png)
![pixel_ROC](https://user-images.githubusercontent.com/6490927/209113482-61325d41-68d7-450f-8ba2-7ec2fa73a9cc.png)

PatchCore
PADIM
Cflow
...
The effect is not ideal

image_size
Check whether the small block is correct
If the image is too small, the defects will not be seen clearly

Can send datasets to your mail
