### ISSUE TITLE
[Bug]: Non-deterministic behaviour for STFPM with fixed seed

### ISSUE THREAD

**Issue by djdameln** [openvinotoolkit/anomalib#814]
### Describe the bug

When training an STFPM model, the results seem to be non-deterministic, even though the seed is fixed.

### Dataset

MVTec

### Model

STFPM

### Steps to reproduce the behavior

1. Run training entrypoint script for STFPM with default settings, and a fixed seed.
2. Repeat step 1 several times and collect performance numbers of the different runs,

### OS information

OS information:
- OS: Ubuntu 20.04
- Python version: 3.8.13
- Anomalib version: Github main branch
- PyTorch version: 1.12.1+cu113
- CUDA/cuDNN version: 11.3
- GPU models and configuration: GeForce RTX 3090

### Expected behavior

The performance numbers are the same for every run.

### Screenshots

These are some results of different runs:
```
       image_AUROC          0.9015873074531555
      image_F1Score         0.9076922535896301
       pixel_AUROC          0.7951012253761292
      pixel_F1Score         0.26678332686424255

       image_AUROC           0.884920597076416
      image_F1Score         0.8857142925262451
       pixel_AUROC          0.7966859340667725
      pixel_F1Score         0.26495227217674255

       image_AUROC          0.9968253970146179
      image_F1Score         0.9921259880065918
       pixel_AUROC          0.9784383177757263
      pixel_F1Score         0.7150415778160095
```

### Pip/GitHub

GitHub

### What version/branch did you use?

main branch

### Configuration YAML

```yaml
dataset:
  name: mvtec #options: [mvtec, btech, folder]
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  inference_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: stfpm
  backbone: resnet18
  layers:
    - layer1
    - layer2
    - layer3
  lr: 0.4
  momentum: 0.9
  weight_decay: 0.0001
  early_stopping:
    patience: 3
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null #options: onnx, openvino
# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 100
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0
```

### Logs

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
