### ISSUE TITLE
[Bug]: Ignore dotfiles in datasets - datamodule.setup() assertion failed

### ISSUE THREAD

**Issue by stillgreyfox** [openvinotoolkit/anomalib#865]
### Describe the bug

Working with 000_getting_started.ipynb

Got assertion fail when calling:

datamodule.setup()  # Downloads the dataset if it's not in the specified `root` directory

AssertionFail "Mismatch between anomalous images and ground truth masks. ..."

Traces to line 133: anomalib/data/mvtec.py

    # assert that the right mask files are associated with the right test images
    assert (
        samples.loc[samples.label_index == 1]
        .apply(lambda x: Path(x.image_path).stem in Path(x.mask_path).stem, axis=1)
        .all()
    ), "Mismatch between anomalous images and ground truth masks. Make sure the mask files in 'ground_truth' \
              folder follow the same naming convention as the anomalous images in the dataset (e.g. image: '000.png', \
              mask: '000.png' or '000_mask.png')."

I inserted some debug prints above this to see contents of samples and samples.loc[samples.label_index == 1]

Noticed something weird in the detected 'label' column
Had values of '.ipynb_checkpoints'

What happened was I browsed into the dataset from JupyterLab's file explorer, and checked out some of the images, and didn't realize a Jupyter autosave happened / I manually saved my modified getting started notebook, and it created a .ipynb_checkpoints directory in the browsed location.

The above is a Jupyter issue, yes, but would be nice not to have cryptic break due to a dotted directory.

My workaround was to clean my datasets dir using a find + xargs combo to delete any dangling .ipynb_checkpoints dirs:

`find /datasets_base_path -type d -name "*.ipynb_checkpoints*" | xargs rm -rf`

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

0. Have MVTec dataset already installed
1. Open anomalib/notebooks/000_getting_started/001_getting_started.ipynb
2. In JupyterLab, browse to MVTec/bottle/ground_truth/broken_large/ in it's file explorer (any subdir of bottle should work)
3. Make a change to the opened notebook (set the path of the MVTec dataset (for example))
4. Save changes to the opened notebook
5. Run the notebook as instructed, up to the cell where you are trying to call `datamodule.setup()  # Downloads the dataset if it's not in the specified `root` directory`
 (after Markdown cell with '## Dataset: MVTec AD')
6. Get assertion fail
7. Discover a new directory:  MVTec/bottle/ground_truth/broken_large/.ipynb_checkpoints/ now exists and is the root of the problem
8. Delete the .ipynb_checkpoints/ dir (and any others contaminating the dataset
   (workaround on linux below)
`find /datasets_base_path -type d -name "*.ipynb_checkpoints*" | xargs rm -rf`
9. Retry step 5 (datamodule.setup()) and it works!

### OS information

OS information:
- OS: Ubuntu 20.04
- Python version: 3.8.10
- Anomalib version: 0.3.7 / latest git clone
- PyTorch version: 1.13.0
- CUDA/cuDNN version: uninstalled by pip requirements / would be 11.6 if I reinstall
- GPU models and configuration: GeForce RTX 3070ti
- Any other relevant information N/A

### Expected behavior

Successfully create the dataframe

### Pip/GitHub

GitHub

### What version/branch did you use?

commit 8a6c6ea115ad2c460a9beaee85736d1180eaa996 (HEAD -> main, origin/main, origin/da /shanghaitech, origin/HEAD)

### Configuration YAML

```yaml
default padim config.yaml

dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.
```

### Logs

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[9], line 5
      1 datamodule = get_datamodule(config)
      2 # MAKE SURE THE DATASET IS CLEAN -- got '.ipynb_checkpoints/' in it from browsing in jupyter?
      3 # clean it up with this:
      4 #!find /notebooks/gh/datasets -type d -name "*.ipynb_checkpoints*" | xargs rm -rf
----> 5 datamodule.setup()  # Downloads the dataset if it's not in the specified `root` directory
      6 datamodule.prepare_data()  # Create train/val/test/prediction sets.
      8 i, data = next(enumerate(datamodule.val_dataloader()))

File /notebooks/gh/anomalib/anomalib/data/base/datamodule.py:102, in AnomalibDataModule.setup(self, stage)
     96 """Setup train, validation and test data.
     97 
     98 Args:
     99   stage: Optional[str]:  Train/Val/Test stages. (Default value = None)
    100 """
    101 if not self.is_setup:
--> 102     self._setup(stage)
    103 assert self.is_setup

File /notebooks/gh/anomalib/anomalib/data/base/datamodule.py:118, in AnomalibDataModule._setup(self, _stage)
    115 assert self.train_data is not None
    116 assert self.test_data is not None
--> 118 self.train_data.setup()
    119 self.test_data.setup()
    121 self._create_test_split()

File /notebooks/gh/anomalib/anomalib/data/base/dataset.py:161, in AnomalibDataset.setup(self)
    159 """Load data/metadata into memory."""
    160 if not self.is_setup:
--> 161     self._setup()
    162 assert self.is_setup, "setup() should set self._samples"

File /notebooks/gh/anomalib/anomalib/data/mvtec.py:172, in MVTecDataset._setup(self)
    171 def _setup(self):
--> 172     self.samples = make_mvtec_dataset(self.root_category, split=self.split, extensions=IMG_EXTENSIONS)

File /notebooks/gh/anomalib/anomalib/data/mvtec.py:133, in make_mvtec_dataset(root, split, extensions)
    130 samples.loc[(samples.split == "test") & (samples.label_index == 1), "mask_path"] = mask_samples.image_path.values
    132 # assert that the right mask files are associated with the right test images
--> 133 assert (
    134     samples.loc[samples.label_index == 1]
    135     .apply(lambda x: Path(x.image_path).stem in Path(x.mask_path).stem, axis=1)
    136     .all()
    137 ), "Mismatch between anomalous images and ground truth masks. Make sure the mask files in 'ground_truth' \
    138           folder follow the same naming convention as the anomalous images in the dataset (e.g. image: '000.png', \
    139           mask: '000.png' or '000_mask.png')."
    141 if split:
    142     samples = samples[samples.split == split].reset_index(drop=True)

AssertionError: Mismatch between anomalous images and ground truth masks. Make sure the mask files in 'ground_truth'               folder follow the same naming convention as the anomalous images in the dataset (e.g. image: '000.png',               mask: '000.png' or '000_mask.png').
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
