### ISSUE TITLE
[Bug]:  CFA OpenVINO inference error

### ISSUE THREAD

**Issue by joelbudu** [openvinotoolkit/anomalib#956]
### Describe the bug

When I try to use the openvino inferencer for a CFA model I get the following error:

  predictions = self.inferencer.predict(image=image)
  File "/usr/local/lib/python3.8/site-packages/anomalib/deploy/inferencers/base_inferencer.py", line 85, in predict
    output = self.post_process(predictions, meta_data=meta_data)
  File "/usr/local/lib/python3.8/site-packages/anomalib/deploy/inferencers/openvino_inferencer.py", line 178, in post_process
    anomaly_map, pred_score = self._normalize(
  File "/usr/local/lib/python3.8/site-packages/anomalib/deploy/inferencers/base_inferencer.py", line 154, in _normalize
    pred_scores = normalize_min_max(
  File "/usr/local/lib/python3.8/site-packages/anomalib/post_processing/normalization/min_max.py", line 28, in normalize
    raise ValueError(f"Targets must be either Tensor or Numpy array. Received {type(targets)}")
ValueError: Targets must be either Tensor or Numpy array. Received <class 'numpy.int32'>

### Dataset

Other (please specify in the text field below)

### Model

Other (please specify in the field below)

### Steps to reproduce the behavior

1. Install anomalib using pip
2.  Train a CFA model
3. Run the OpenVINO inferencer on a sample image

### OS information

OS information:
- Python version: 3.8
- Anomalib version: 0.4.0
- PyTorch version: [e.g. 1.13.1]
- CUDA/cuDNN version: 11.1
- 
I'm using a custom dataset

### Expected behavior

Expected to have a predicted result

### Pip/GitHub

pip

### What version/branch did you use?

v0.4.0

### Configuration YAML

```yaml
dataset:
  name: grapes
  format: folder
  path: /content/drive/MyDrive/anomaly_det/datasets/ds
  task: segmentation
  train_batch_size: 2
  eval_batch_size: 2
  inference_batch_size: 2
  num_workers: 8
  image_size:
  - 512
  - 512
  center_crop: null
  normalization: imagenet
  normal_dir: good
  abnormal_dir: defective
  normal_test_dir: null
  mask: mask
  extensions: null
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir
  test_split_ratio: 0.5
  val_split_mode: same_as_test
  val_split_ratio: 0.5
  mask_dir: mask
  root: /content/drive/MyDrive/anomaly_det/datasets/ds
model:
  name: cfa
  backbone: wide_resnet50_2
  gamma_c: 1
  gamma_d: 1
  num_nearest_neighbors: 3
  num_hard_negative_features: 3
  radius: 1.0e-05
  lr: 0.001
  weight_decay: 0.0005
  amsgrad: true
  early_stopping:
    patience: 5
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max
  input_size:
  - 512
  - 512
metrics:
  image:
  - AUROC
  pixel:
  - AUROC
  threshold:
    adaptive: true
    image_default: null
    pixel_default: null
    method: adaptive
    manual_image: null
    manual_pixel: null
visualization:
  show_images: false
  save_images: true
  log_images: true
  image_save_path: null
  mode: full
project:
  seed: 0
  path: results/cfa/grapes/run
  unique_dir: false
logging:
  logger:
  - wandb
  log_graph: false
optimization:
  export_mode: openvino
trainer:
  enable_checkpointing: true
  default_root_dir: results/cfa/grapes/run
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 30
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 50
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
predictions = self.inferencer.predict(image=image)
  File "/usr/local/lib/python3.8/site-packages/anomalib/deploy/inferencers/base_inferencer.py", line 85, in predict
    output = self.post_process(predictions, meta_data=meta_data)
  File "/usr/local/lib/python3.8/site-packages/anomalib/deploy/inferencers/openvino_inferencer.py", line 178, in post_process
    anomaly_map, pred_score = self._normalize(
  File "/usr/local/lib/python3.8/site-packages/anomalib/deploy/inferencers/base_inferencer.py", line 154, in _normalize
    pred_scores = normalize_min_max(
  File "/usr/local/lib/python3.8/site-packages/anomalib/post_processing/normalization/min_max.py", line 28, in normalize
    raise ValueError(f"Targets must be either Tensor or Numpy array. Received {type(targets)}")
ValueError: Targets must be either Tensor or Numpy array. Received <class 'numpy.int32'>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aadhamm** [comment]
The solution for the value error here is simple, your input was read in a format, that is not compatible with the model, it's just I don't understand where your input or dataset came from, depending on Numpy and Torch libraries

however, here is a simple code to convert your image input to a tensor format, depending on Numpy and Torch libraries, so inference can be done:

`img = torch.from_numpy(np.transpose(img[:, :, [2, 1, 0]],
                                        (2, 0, 1))).float()`
`img = img.unsqueeze(0).to('cpu')`

**Comment by joelbudu** [comment]
I'm supplying an image in numpy format.

This only happens in the Openvino version of the inferencer and I have the same pipeline for other models in anomalib which work fine.

**Comment by samet-akcay** [comment]
Hi @joelbudu, if you experience this issue only when you try CFA, it is probably because of the following line

https://github.com/openvinotoolkit/anomalib/blob/9eca34f8b490ae6c58aed4421fb94dcb75b1c8e5/src/anomalib/models/cfa/torch_model.py#L164

We are still using scikit learns `KMeans`. We need to port that to Torch to be able to convert it to ONNX and OpenVINO

**Comment by aadhamm** [comment]
Dear, @samet-akcay, I don't know if this is an existing issue, but as being willing to contribute to Anomalib in Google Summer of Code, I want to investigate Anomalib more,

so if it is possible, I  propose implementing the KMeans algorithm `in the Torch framework` instead of using the `scikit-learn implementation` to fix this issue.

Thank you

**Comment by samet-akcay** [comment]
@aadhamm, yeah this has been on our to do list for a while, but we didn't have time to implement.

If you are willing to implement, you're more than welcome :)

**Comment by aadhamm** [comment]
@samet-akcay Very well :)

**Comment by aadhamm** [comment]
Dear @samet-akcay, to just share with you, I have got my hands on a PyTorch implementation for the Kmeans clustering algorithm and compared its results with the sklearn implementation using random input data, resulting in `an identical Silhouette score of 0.58,`

what I will do now is keep iterating the code more and search for any other methods of validation for this implementation and if possible, I may show you the code or make a pull request directly, I hope you help me with a guide in that and if you have in mind anything I should do that will help me.

Thank you.

![image](https://user-images.githubusercontent.com/86083079/229346935-d2b97fa8-8f6c-44d2-a70e-2ba3b8bcddf4.png)

**Comment by samet-akcay** [comment]
@aadhamm, looking quite promising! Thanks!

**Comment by aadhamm** [comment]
Dear @samet-akcay, please find my pull request #998 

and waiting for your feedback.

Thank you

**Comment by Kyle-fang** [comment]
Hello! I used onnxruntime to reason about onnx model and got the output as an anomaly map of [1, 1, 256, 256], but I want to know if the current image is an anomaly or a person normal sample what should I do? Is there code to accomplish this? @aadhamm @samet-akcay

**Comment by samet-akcay** [comment]
@joelbudu, this cannot be reproduced if the latest anomalib version is used. I've used the following configuration file for the CFA model that is trained on the hazelnut dataset that could be downloaded from here:

```yaml
dataset:
  name: hazelnut_toy
  format: folder
  root: ./datasets/hazelnut_toy
  normal_dir: good
  abnormal_dir: colour
  normal_test_dir: null
  mask_dir: mask/colour
  extensions: null
  task: segmentation
  train_batch_size: 2
  eval_batch_size: 2
  inference_batch_size: 2
  num_workers: 8
  image_size: 512 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir
  test_split_ratio: 0.5
  val_split_mode: same_as_test
  val_split_ratio: 0.5


model:
  name: cfa
  backbone: wide_resnet50_2
  gamma_c: 1
  gamma_d: 1
  num_nearest_neighbors: 3
  num_hard_negative_features: 3
  radius: 1e-5
  lr: 1e-3
  weight_decay: 5e-4
  amsgrad: true
  early_stopping:
    patience: 5
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - AUROC
  pixel:
    - AUROC
  threshold:
    adaptive: true
    image_default: null
    pixel_default: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

Then used the following command to perform the OpenVINO inference:

```bash
python tools/inference/openvino_inference.py \
        --weights results/cfa/hazelnut_toy/run/weights/openvino/model.bin \
        --metadata results/cfa/hazelnut_toy/run/weights/openvino/metadata.json \
        --input datasets/hazelnut_toy/colour/01.jpg \
        --output results/cfa/hazelnut_toy/run/outputs/000.png
```

Since it is now irreproducible, I'll close the issue. If you still have an issue, feel free to re-open it. Thanks for your patience!
