### ISSUE TITLE
[Bug]: generate_output_image_filename not working when dir doesn't exist

### ISSUE THREAD

**Issue by blaz-r** [openvinotoolkit/anomalib#970]
### Describe the bug

Function `generate_output_image_filename` from `anomalib.data.utils.image` doesn't work if the output file is a directory that doesn't yet exist. That is because it checks if path is a directory and if it is, it appends a filename, if it isn't (or doesn't exist) it assumes it's a file and just leaves path as is.
This is used in torch_inference and openvino_inference, but not in lightning_inference. In lightning, ImageVisualizerCallback is used, which assumes that the path is a directory, so it always appends the filename so the problem doesn't occur.

That is:
when `datasets/MVTec/bottle/test/broken_large/000.png` is given as input and `results/padim/mvtec/bottle/images` is as output, but `results/padim/mvtec/bottle/images` doesn't exist:
produced path should be `results/padim/mvtec/bottle/images/broken_large/000.png`.
but instead `results/padim/mvtec/bottle/images` is produced.

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

1. Checkout main branch
2. Enable openvino export in config.yaml
3. Train model `python tools/train.py --model padim`
4. Test inference using open_vino
```bash
python tools/inference/openvino_inference.py \
    --config src/anomalib/models/padim/config.yaml \
    --weights results/padim/mvtec/bottle/run/openvino/model.bin \
    --metadata results/padim/mvtec/bottle/run/openvino/metadata.json \
    --input datasets/MVTec/bottle/test/broken_large/000.png \
    --output results/padim/mvtec/bottle/images
```

### OS information

OS information:
- OS: WIndows 10
- Python version: 3.8.10
- Anomalib version: 0.5.0.dev0
- PyTorch version: 2.0.0
- CUDA/cuDNN version: /
- GPU models and configuration: MX250
- Any other relevant information: /

### Expected behavior

output results/padim/mvtec/bottle/images directory should be created and exact path returned.
produced path should be `results/padim/mvtec/bottle/images/broken_large/000.png`.

### Screenshots

![error](https://user-images.githubusercontent.com/61357777/226180665-48d4f284-ebfe-468b-83d3-142dfb1bd85a.png)
Happens because path to file is given as:
`results/padim/mvtec/bottle/images`  instead of `results/padim/mvtec/bottle/images/broken_large/000.png`

### Pip/GitHub

GitHub

### What version/branch did you use?

main

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  category: bottle
  task: segmentation
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
